import {StyleSheet} from "react-native"

export let styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 0,
    backgroundColor: 'transparent',
  },
  cartButton: {
    position: 'relative',
  },
  cartBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: 'red',
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartCount: {
    color: 'white',
    fontSize: 12,
  },
  categoriesContainer: {
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: 'transparent',
    minHeight: 0,
    maxHeight: 56,
  },
  categoriesContent: {
    alignItems: 'center',
    paddingHorizontal: 8,
    minHeight: 0,
  },
  categoryPill: {
    backgroundColor: '#23242a',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginRight: 8,
    minHeight: 32,
    minWidth: 0,
    elevation: 0,
  },
  categoryPillActive: {
    backgroundColor: '#4F8EF7',
  },
  categoryPillText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  categoryPillTextActive: {
    color: '#fff',
  },
  menuContainer: {
    flex: 1,
    padding: 8,
    backgroundColor: 'transparent',
  },
  menuItemCard: {
    flexDirection: 'row',
    marginBottom: 18,
    backgroundColor: '#181A20',
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
    padding: 0,
  },
  menuItemImage: {
    width: 90,
    height: 90,
    backgroundColor: '#23242a',
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
  },
  menuItemInfo: {
    flex: 1,
    padding: 14,
  },
  menuItemName: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  menuItemDescription: {
    fontSize: 14,
    color: '#bbb',
    marginBottom: 4,
  },
  menuItemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4F8EF7',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: '#181A20',
    borderRadius: 18,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 8,
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 2,
    backgroundColor: '#23242a',
    borderRadius: 16,
    padding: 4,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    marginTop: 8,
    textAlign: 'center',
  },
  modalDescription: {
    fontSize: 15,
    color: '#bbb',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalPrice: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4F8EF7',
    marginBottom: 18,
    textAlign: 'center',
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
    backgroundColor: '#23242a',
    borderRadius: 20,
    padding: 8,
  },
  quantityButton: {
    padding: 8,
  },
  quantityText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginHorizontal: 16,
  },
  commentsInput: {
    borderWidth: 1,
    borderColor: '#23242a',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    minHeight: 60,
    backgroundColor: '#181A20',
    color: '#fff',
  },
  addButton: {
    backgroundColor: '#4F8EF7',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  addButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cartItems: {
    maxHeight: 220,
    marginVertical: 10,
  },
  cartItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#23242a',
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemName: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 2,
  },
  cartItemQuantity: {
    fontSize: 14,
    color: '#bbb',
  },
  cartItemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4F8EF7',
    marginLeft: 8,
  },
  cartTotalRow: {
    marginTop: 10,
    alignItems: 'flex-end',
  },
  cartTotalText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  confirmButton: {
    backgroundColor: '#34C759',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  confirmButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  deleteButton: {
    marginLeft: 10,
    padding: 4,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
